#+TITLE: Emacs Mini Manual (PART 3) - CUSTOMIZING AND EXTENDING EMACS
* Whny customize and extend Emacs?
:PROPERTIES:
:ID:       84576135-507c-41ad-b122-2dd498235ecf
:END:
Emacs comes with a default settings. Some interesting features are
disabled and hidden, i.e. Ibuffer, Semantic, electric
modes... Probably to make it more user friendly to new users and
behave more like "normal" editors, i.e. Normal users do not expect
automatic pairing of punctuation marks like parentheses, brackets,
curly brackets...

Because the nature of Emacs is an extensible system, people write
extensions to improve Emacs and share with others. The extensions
improve various aspects of Emacs: Improve and add editing features,
integrate 3rd party tools, add programming languages supports, change
Emacs appearance... Without the ability to extend, Emacs will just be
another obscure editor with some useful features but cannot meet the
demands of people, because different people have different needs, and
Emacs maintainers cannot provide them all and integrate all into
Emacs. With the extensibility, people can bend Emacs the way they
want, much like Lisp.

Unlike other editors which encourage users to stay with the default as
much as they can, Emacs encourages users to customize and extend Emacs
as much as they can.
* Just enough Emacs Lisp (and Lisp in general)
:PROPERTIES:
:ID:       267fa5b6-b998-42c6-8ec0-382035284873
:END:
In this section, you only need to read and understand. It's important
that you understand the core ideas. After you finish the sub-sections
of this section, we will play with Emacs Lisp code for customizing
Emacs, and it's really fun to see your Emacs "evolves" gradually.
** Commonly used functions and patterns for configuration
:PROPERTIES:
:ID:       e54be9d4-bce0-428e-94be-c137bdc0de11
:END:
In this section, I will list the basic usage of popular functions that
are used to configure Emacs. If you want to understand more, *C-h
f* and enter name of the function. All of the quoted function
descriptions are taken from *C-h f*. If you forget what a function
does and how to use it, *C-h f* to find out. Really, you should get
used to getting help from Emacs.

- Function: =(load /FILE/ &optional /NOERROR/ /NOMESSAGE/ /NOSUFFIX/ /MUST-SUFFIX/)=

  *_Example_*: 

  #+begin_src emacs-lisp
    (load (substitute-in-file-name "$HOME/.emacs.d/module")) ;; first try to load module.elc; if not found, try to load module.el
    (load (substitute-in-file-name "$HOME/.emacs.d/module.el")) ;; only load module.el
    (load (substitute-in-file-name "$HOME/.emacs.d/module.elc")) ;; only load module.elc
  #+end_src

  *_Comment_*:
   
  *_Built-in description_*:
   
  #+BEGIN_QUOTE
  Execute a file of Lisp code named FILE.
  First try FILE with `.elc' appended, then try with `.el', then try
  FILE unmodified (the exact suffixes in the exact order are determined
  by `load-suffixes').  Environment variable references in FILE are
  replaced with their values by calling `substitute-in-file-name'. This
  function searches the directories in `load-path'. 
   
  ....(*C-h f* for more information)...
  #+END_QUOTE

- Function: =(global-set-key /KEY/ /COMMAND/)=

  *_Example_*:
   
  #+begin_src emacs-lisp
    (global-set-key (kbd "C-x C-b") 'ibuffer) ;; bind "C-x C-b" to ibuffer command
    (global-set-key "\C-x\C-b" 'ibuffer)  ;; bind "C-x C-b to ibuffer command, but modifier 
                                          ;; keys must be escaped with the backslash
    (global-set-key [?\C-x?\C-b] 'ibuffer) ;; use vector instead of a string
  #+end_src
   
  I recommend you to use =(kbd ...)= function because we can write key
  bindings using our familiar key notations without adding unnecessary
  characters. Vector is array in other languags. Vector was used for
  mapping function keys, such as =[left]=, =[right]=, =[up]=, =[down]=,
  =[f1]...[f12]=. But now, you can also map function keys in =(kbd
  ...)= function using angle brackets:
   
  #+begin_src emacs-lisp
    (global-set-key (kbd "<f3>") 'kmacro-start-macro-or-insert-counter)0
  #+end_src
   
  Here are common function keys: 
   
  | Key                                              | Description                                        |
  |--------------------------------------------------+----------------------------------------------------|
  | =left, up, right, down=                          | Cursor arrow keys                                  |
  |--------------------------------------------------+----------------------------------------------------|
  | =begin, end, home, next, prior=                  | Other cursor repositioning keys                    |
  |                                                  | =prior= means =PageUp=                             |
  |                                                  | =next= means =PageDOwn=                            |
  |--------------------------------------------------+----------------------------------------------------|
  | =select, print, execute, backtab=                | Miscellaneous keys                                 |
  | =insert, undo, redo, clearline=                  | =backtab= means =S-TAB= or =C-iso-tab=             |
  | =insertline, deleteline, insertchar, deletechar= |                                                    |
  |--------------------------------------------------+----------------------------------------------------|
  | =f1, f2, ... F35=                                | Numbered function keys on top of your keyboard     |
  |--------------------------------------------------+----------------------------------------------------|
  | =kp-add, kp-subtract, kp-multiply, kp-divide=    | Keypad keys (to the right of the regular keyboard) |
  | =kp-backtab, kp-space, kp-tab, kp-enter=         | , with names or punctuation.                       |
  | =kp-separator, kp-decimal, kp-equal=             |                                                    |
  |                                                  |                                                    |
  | =kp-0, kp-1, ... kp-9=                           | Keypad keys with digits.                           |
  |                                                  |                                                    |
  | =kp-f1, kp-f2, kp-f3, kp-f4=                     | Keypad PF keys.                                    |
  |--------------------------------------------------+----------------------------------------------------|
   
  *_Built-in description_*:
   
  #+BEGIN_QUOTE
  Give /KEY/ a global binding as /COMMAND/.
  /COMMAND/ is the command definition to use; usually it is
  a symbol naming an interactively-callable function.
  /KEY/ is a key sequence; noninteractively, it is a string or vector
  of characters or event types, and non-ASCII characters with codes
  above 127 (such as ISO Latin-1) can be included if you use a vector.
   
  Note that if /KEY/ has a local binding in the current buffer,
  that local binding will continue to shadow any global binding
  that you make with this function.
  #+END_QUOTE
   
- Function: =(global-unset-key /KEY/)=
  *_Example_*:

  #+begin_src emacs-lisp
    (global-unset-key (kbd "C-x b"))
    (global-set-key (kbd "C-x b a") 'switch-to-buffer)
    (global-set-key (kbd "C-x b b") 'ibuffer)
  #+end_src
  
  *_Comment_*: A function to unset a key in global keymap. It's useful
  if you want to turn a key binding into a prefix key. For example,
  =C-x m= binding is =compose-mail=. But for example, you want to bind
  =C-x b a= to =switch-to-buffer= and =C-x b b= to =ibuffer=, two commands of your
  choice (this is just an example; you should use these bindings). To
  do that, first you have to unset =C-x m=; only then, you will be
  able to bind the keys. Otherwise, Emacs won't allow because
  prefix key =C-x b= is alreay used to something else. Try the above
  example with *C-x e*. To get your old bindings back, execute this
  snippet:

  #+begin_src emacs-lisp
    (global-unset-key (kbd "C-x b a"))
    (global-unset-key (kbd "C-x b b"))
    (global-set-key (kbd "C-x b") 'switch-to-buffer)
  #+end_src

  *_Built-in description_*:
  #+BEGIN_QUOTE
  (global-unset-key /KEY)

  Remove global binding of /KEY/.
  /KEY/ is a string or vector representing a sequence of keystrokes.
  #+END_QUOTE

- Function: =(define-key /KEYMAP/ /KEY/ /DEF/)=
  
  *_Example_*:
  

** Configuration collector
:PROPERTIES:
:ID:       31381170-81ba-413a-8b3e-b701bd62c30c
:END:

* Useful built-in key bindings for navigating pairs
:PROPERTIES:
:ID:       1a1248d4-2a59-4c80-a5c5-e471adc40c8f
:END:

| Key         | Binding                                  |
|-------------+------------------------------------------|
| =C-M-f=     | *Command*: =forward-sexp=                |
|             | Move forward over a balanced expression  |
|             | ...[screenshot]...                       |
|-------------+------------------------------------------|
| =C-M-b=     | *Command*: =backward-sexp=               |
|             | Move backward over a balanced expression |
|             | ...[screenshot]...                       |
|-------------+------------------------------------------|
| =C-M-k=     | *Command*: =kill-sexp=                   |
|             | Kill balanced expression forward         |
|             | ...[screenshot]...                       |
|-------------+------------------------------------------|
| =C-M-t=     | *Command*: =transpose-sexps=             |
|             | Transpose expressions                    |
|             | ...[screenshot]...                       |
|-------------+------------------------------------------|
| =C-M-<SPC>= | *Command*: =mark-sexp=                   |
| =C-M-@=     | Put mark after following expression      |
|             | ...[screenshot]...                       |
|-------------+------------------------------------------|

* Let's supercharge Emacs
:PROPERTIES:
:ID:       8d44370b-5ab7-40fc-9a72-1ef9dc66ffd2
:END:
Throughout this section I will help you to extend Emacs with packages
that improves general Emacs features, such as Info, Dired, buffer
management... I will introduce you popular packages out there, but I
cannot present you all. The purpose of this guide is to help you get
really comfortable to Emacs package system, so you can extend Emacs
with packages from other people easily to fit your need. Extending
Emacs on your own is a differnt story, and is beyond the scope of this
guide.

I will introduce packages specialized for programming in Part 3: how
to setup programming environment for popular languages (C/C++, Lisp,
Python, Ruby...). In this part of the mini manual series, I only
introduce general packages for extending Emacs in various aspects. And
you are going to need some of these packages to setup your specialized 
programming envrionment, so don't skip it.

Don't be intimidated if you see many packages down there. Adding
packages and see it extends your Emacs is fun and addictive, like 
playing video games.

To remind you, Emacs always loads one of the three of the following
files when it starts:

- ~/.emacs
- ~/.emacs.d/init
- ~/.emacs.d/init.el

To apply a setting, move point to the end of a Lisp expression and
*C-x C-e*, which runs =eval-last-sexp=.

When you want to complete function names in Emacs Lisp: *C-M-i*,
which runs =completion-at-point=. It will display a list of possible
candidates available in Emacs. 

If you want to quickly complete something, you can *M-/*, which runs
=dabbrev-expand=.

** How to use Emacs package manager
:PROPERTIES:
:ID:       d0b0f0d6-3662-4be3-84e7-342735015170
:END:
** setup-general.el
:PROPERTIES:
:ID:       2f850290-6962-49f0-aea6-d735aa8bfbd9
:END:
- Function: =(setq [ /SYM/ /VAL/ ]...)=

  *_Comment_*: A really fundamental function for customizing Emacs
  settings. 

  *_Built-in descriptions_*:
  #+BEGIN_QUOTE
  Set each /SYM/ to the value of its /VAL/.
  The symbols /SYM/ are variables; they are literal (not evaluated).
  The values /VAL/ are expressions; they are evaluated.
  Thus, (setq x (1+ y)) sets `x' to the value of `(1+ y)'.
  The second /VAL/ is not computed until after the first /SYM/ is set, and so on;
  each VAL can use the new value of variables set earlier in the `_setq_'.
  The return value of the `_setq_' form is the value of the last /VAL/.
  #+END_QUOTE

  Let's use =setq= to change Emacs the way we want. You should type in
  the snippet below and use the completion key bindings until you get
  used to it.

  #+begin_src emacs-lisp
    ;; you can set a value to one variablea
    (setq gc-cons-threshold 50000000)       ;; only activate garbage collection every 50MB to improve performance
    (setq                                   ;; or you can set multiple values to multiple variables
     inhibit-startup-message t
     kill-ring-max 5000                     ;; increase kill ring up to 5000 entries before it pops the oldest one out
     mark-ring-max 5000                     ;; increase kill ring up to 5000 entries before it pops the oldest one out
     require-final-newline t                ;; auto add newline at the end of file
     column-number-mode t                   ;; show the column number
     default-major-mode 'text-mode          ;; use text mode per default
     mouse-yank-at-point t                  ;; middle click with the mouse yanks at point
     history-length 250                     ;; default is 30
     locale-coding-system 'utf-8            ;; utf-8 is default
     tab-always-indent 'complete            ;; try to complete before identing
     tab-width 4
     confirm-nonexistent-file-or-buffer nil ;; don't ask to create a buffer
     vc-follow-symlinks t                   ;; follow symlinks automatically
     recentf-max-saved-items 5000           ;; same up to 5000 recent files
     indicate-buffer-boundaries 'left       ;fringe markers
     split-height-threshold 110             ;more readily split horziontally
     enable-recursive-minibuffers t
     custom-unlispify-menu-entries nil      ;M-x customize should not cripple menu entries
     custom-unlispify-tag-names nil         ;M-x customize should not cripple tags
     show-paren-delay 0
     view-read-only t
     )
  #+end_src
  
Another way to change a setting is using *C-h v*, which runs
=describe-variable= that describes a variable and allow customization
if possible.

You wonder, there are so many variables to set. How do you know which
to which? Luckily, you don't have to manually guess which variable to
set. Emacs has a command for setting Emacs internally, with a nice
organization of settings, rather than randomly set a variable that you
randomly found. =M-x customize= to open a window for customizing Emacs.
*** Built-in: recentf
:PROPERTIES:
:ID:       9daec59b-8c5e-4712-955d-be3b3414ad83
:END:

*** Package: recentf-ext
:PROPERTIES:
:ID:       8013594a-f2f3-477c-820c-caf1354ac23d
:END:

*** Package: ibuffer-git
:PROPERTIES:
:ID:       094b65d3-8969-4603-9ce8-2930c1927b95
:END:
*** Package: ibuffer-vc
:PROPERTIES:
:ID:       7b0b29a2-6a13-4b39-bbec-bb52ff97783b
:END:
*** Package: ztree
:PROPERTIES:
:ID:       509e175b-8d72-472d-ad1c-7e96c647cb77
:END:

** setup-ui.el
:PROPERTIES:
:ID:       0c54618f-8c80-4f47-9cb7-a7003fab46ab
:END:

*** Chagning Emacs apperance
:PROPERTIES:
:ID:       25197681-292e-47d4-89ff-53658862068b
:END:
** setup-editor.el
:PROPERTIES:
:ID:       f3eab381-cb88-4e5a-8ff1-24cdb454a744
:END:

*** Enable built-ins
:PROPERTIES:
:ID:       0de2d016-c00f-4ea3-b3d4-e1f743713d4a
:END:

*** Built-in: linum
:PROPERTIES:
:ID:       0e4a2f8e-fc8d-418c-b25f-c6edecb018da
:END:

*** Built-in: electric-indent-mode
:PROPERTIES:
:ID:       d24019dc-6950-479a-a22c-f015a5143b05
:END:
*** Built-in: whitespace-mode
:PROPERTIES:
:ID:       8ae7f455-0457-46f0-86ff-f3b8d3658ff0
:END:
*** Package: clean-aindent-mode
:PROPERTIES:
:ID:       f15a2012-97ad-4de7-b7b3-f0cb94dfd9d2
:END:
*** Package: smartparens-mode
:PROPERTIES:
:ID:       4a1b2e00-b23b-4104-b60d-4e44465b858a
:END:

**** Alternatives
:PROPERTIES:
:ID:       4f255ca3-8ad9-4316-a30a-6305c5715377
:END:

*** Package: ace-jump-mode
:PROPERTIES:
:ID:       8c648eca-d6fe-411f-913f-479de76c138a
:END:
*** Package: diff-hl
:PROPERTIES:
:ID:       c308752e-4f95-4409-8921-1e905aa73884
:END:
*** Package: expand-region
:PROPERTIES:
:ID:       6c217940-9a70-4654-8b55-38a3f99e12d3
:END:
*** Package: easy-kill
:PROPERTIES:
:ID:       2d0dc98b-3e5c-403e-9cc4-3dd8934c69cd
:END:
*** Package: highlight-symbol
:PROPERTIES:
:ID:       c8c4279b-263c-4b7c-b370-ff465a357e92
:END:
*** Package: multiselect
:PROPERTIES:
:ID:       684f1185-fc42-42d2-8b26-f9e972f3fb83
:END:
*** Package: pretty-lambdada
:PROPERTIES:
:ID:       9bdee173-eea2-4ffe-9da5-51abcba85d66
:END:
*** Package: hippie-expand
:PROPERTIES:
:ID:       d308b663-9560-4c44-800f-e91757228590
:END:
*** Package: rainbow-mode
:PROPERTIES:
:ID:       2f37c16a-307a-4683-adf5-31a64c0817d5
:END:
*** Package: rawinbow-delimiter
:PROPERTIES:
:ID:       4ea22f1a-a72e-4ee9-b54f-88d866f25666
:END:
*** Package: yasnippet
:PROPERTIES:
:ID:       ea795154-fe90-4c00-9874-6b24a36430f0
:END:
*** Package: vlf
:PROPERTIES:
:ID:       175b96e7-c986-407a-b3d1-98c0a417e5de
:END:
*** Package: zop-to-char
:PROPERTIES:
:ID:       699984dc-fff2-4ded-82d2-a8131ab2e801
:END:
*** Package: undo-tree
:PROPERTIES:
:ID:       e4e1faa4-3fa4-4424-943b-94b626da982e
:END:

*** Package: nyan-mode
:PROPERTIES:
:ID:       77911eb8-f448-475a-a8fb-1546f7b43629
:END:

** setup-ido.el
:PROPERTIES:
:ID:       de428bfd-de8d-4b53-ae08-1b7fd53ff1cb
:END:
** setup-info.el
:PROPERTIES:
:ID:       c94fdf0a-e6ac-49f9-b1cb-611fc9ea4753
:END:

** setup-dired.el
:PROPERTIES:
:ID:       fc2536d4-734f-4887-ad82-fd7d1ad52c06
:END:

** setup-bookmark
:PROPERTIES:
:ID:       5bde4b05-c051-42a2-bc14-8490728f11fa
:END:
** setup-windows.el
:PROPERTIES:
:ID:       738556d6-e56f-464b-87f6-e1d7878f7d5e
:END:
*** Built-in: winner-mode
:PROPERTIES:
:ID:       d90e7bb7-2470-4bae-a184-9c41009098a1
:END:
*** Package: golden-ratio
:PROPERTIES:
:ID:       55499f58-b666-477d-9e81-99cb92464b7f
:END:
*** Package: policty-witch.el
:PROPERTIES:
:ID:       e75cca87-377e-41eb-9b66-4de60814f490
:END:
** setup-projectile.el
:PROPERTIES:
:ID:       024e5f66-8aaa-4fff-a5bf-27468b9548c3
:END:
** setup-eshell.el
:PROPERTIES:
:ID:       b5869f1c-54df-43e5-8eef-d557ef9fdfca
:END:

** setup-company.el
:PROPERTIES:
:ID:       dcf6c7ae-406a-4436-b09e-b1b5c7b554e2
:END:
** setup-helm.el
:PROPERTIES:
:ID:       a0fbf5d8-af3f-4fd8-a7f4-fff006a49fa8
:END:
*** Package: helm-ls-git
:PROPERTIES:
:ID:       790ab1dd-fe07-4b01-bb03-742586e3f6a1
:END:
*** Package: helm-desbinds
:PROPERTIES:
:ID:       46a860a4-4a29-4199-9069-29dd0cc043ea
:END:
*** Package: helm-projectile
:PROPERTIES:
:ID:       7b823d0a-212d-4277-ace2-bc317e196206
:END:

** setup-helps.el
:PROPERTIES:
:ID:       bf450c25-178f-4ab7-b4c9-4bd3475e375b
:END:
*** Package: discover-my-major
:PROPERTIES:
:ID:       92ff6c99-10a8-4779-a293-48b3c36c16bb
:END:

** Extend built-in functionality
:PROPERTIES:
:ID:       f7f5027d-65aa-4e1c-9c8f-d069297a207e
:END:

* More Emacs Lisp resources
:PROPERTIES:
:ID:       71d59853-4e9e-41d5-a0c7-56000cb01fc3
:END:
